name: Build Android APK (produce APK artifact)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project deps (if any)
        run: npm ci || npm install
        working-directory: .

      - name: Ensure Android platform clean
        run: |
          cordova platform rm android || true
          cordova platform add android@10.1.2
        working-directory: .

      - name: Build APK (force APK, not AAB)
        run: cordova build android --release -- --packageType=apk
        working-directory: .

      - name: Show build outputs (debug)
        run: ls -la platforms/android/app/build/outputs || true
        working-directory: .

      - name: Upload generated APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: platforms/android/app/build/outputs/**/*.apk
