name: Build Android APK (produce APK artifact)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repo (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # Step 4: Install project dependencies
      - name: Install project deps
        run: npm ci || npm install
        working-directory: .

      # Step 5: Ensure clean Android platform
      - name: Ensure Android platform clean
        run: |
          cordova platform rm android || true
          cordova platform add android@10.1.2
        working-directory: .

      # Step 6: Build APK (force APK, not AAB)
      - name: Build APK
        run: cordova build android --release -- --packageType=apk
        working-directory: .

      # Step 7: Show build outputs (optional, for debugging)
      - name: Show build outputs
        run: ls -la platforms/android/app/build/outputs || true
        working-directory: .

      # Step 8: Upload generated APK(s) as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: platforms/android/app/build/outputs/**/*.apk
