name: Build Android APK (Cordova 9 fallback)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova@10.0.0

      - name: Install project deps
        run: npm ci || npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          components: platform-tools,platforms;android-30

      - name: Ensure Android platform clean (Cordova-Android 9)
        run: |
          cordova platform rm android || true
          cordova platform add android@9.1.0
        shell: bash

      - name: Build APK
        run: cordova build android --release -- --packageType=apk
        shell: bash

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: platforms/android/app/build/outputs/**/*.apk
