name: Build Android (AAB + APK)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm ci || npm install

      - name: Prepare Android platform
        run: |
          cordova platform remove android || true
          cordova platform add android@14.0.1 --no-interactive

      - name: Build Android AAB
        run: cordova build android --release -- --packageType=bundle

      - name: Build Android APK
        run: cordova build android --release -- --packageType=apk

      - name: Upload build artifacts (AAB + APK)
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            platforms/android/app/build/outputs/bundle/release/app-release.aab
            platforms/android/app/build/outputs/apk/release/app-release.apk
