name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # 4️⃣ Navigate to your app folder
      - name: Navigate to MyAppCordova
        working-directory: MyAppCordova
        run: |
          npm install

      # 5️⃣ Add Android platform (skip if already added)
      - name: Add Android platform
        working-directory: MyAppCordova
        run: |
          cordova platform add android || echo "Android platform already exists"

      # 6️⃣ Build the APK
      - name: Build APK
        working-directory: MyAppCordova
        run: |
          cordova build android --release

      # 7️⃣ Upload the APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: MyAppCordova/platforms/android/app/build/outputs/apk/release/*.apk
