name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g cordova
      - run: npm ci
      - run: cordova platform remove android || true
      - run: cordova platform add android@14.0.1 --no-interactive
      - run: cordova build android --release -- --packageType=bundle

      - uses: actions/upload-artifact@v3
        with:
          name: android-artifacts
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab
